// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.test01;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test01_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test01_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test01_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test01_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\ncom.test01\"\035\n\tMyRequest" +
      "\022\020\n\010userName\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010real" +
      "Name\030\001 \001(\t2Z\n\016StudentService\022H\n\025getRealN" +
      "ameByUserName\022\025.com.test01.MyRequest\032\026.c" +
      "om.test01.MyResponse\"\000B\034\n\ncom.test01B\014St" +
      "udentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_test01_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test01_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test01_MyRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_test01_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test01_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test01_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
