// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.test01;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test01_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test01_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test01_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test01_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test01_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test01_StudentResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\ncom.test01\"\035\n\016StudentRe" +
      "quest\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014\n" +
      "\004name\030\001 \001(\t\022\013\n\003arg\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"K" +
      "\n\023StudentResponseList\0224\n\017studentResponse" +
      "\030\001 \003(\0132\033.com.test01.StudentResponse2f\n\016S" +
      "tudentService\022T\n\021getStudentsByAges\022\032.com" +
      ".test01.StudentRequest\032\037.com.test01.Stud" +
      "entResponseList\"\000(\001B\034\n\ncom.test01B\014Stude" +
      "ntProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_test01_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test01_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test01_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_test01_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test01_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test01_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Arg", "City", });
    internal_static_com_test01_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_test01_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test01_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
