// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.test01;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test01.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.test01.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.test01.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.test01.StudentResponse studentResponse = 1;</code>
   */
  com.test01.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.test01.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.test01.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.test01.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.test01.StudentResponse studentResponse = 1;</code>
   */
  com.test01.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
