// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.test01;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test01.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 1;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
